name: 'Trigger and Monitor Workflow'
description: 'Triggers a workflow in a private repository and monitors its status'
inputs:
  owner:
    description: 'Owner of the repository where the workflow will be triggered'
    required: true
  repo:
    description: 'Repository where the workflow will be triggered'
    required: true
  github_token:
    description: 'GitHub token for authentication'
    required: true
  workflow_file_name:
    description: 'Name of the workflow file to trigger'
    required: true
  ref:
    description: 'Git reference for the workflow (branch or tag name)'
    required: true
  client_payload:
    description: 'JSON payload to send with the workflow dispatch'
    required: false
  wait_interval:
    description: 'Time interval in seconds between status checks'
    required: false
    default: '10'
runs:
  using: 'composite'
  steps:
    - run: bash ${{ github.action_path }}/trigger_script.sh "${{ inputs.owner }}" "${{ inputs.repo }}" "${{ inputs.github_token }}" "${{ inputs.workflow_file_name }}" "${{ inputs.ref }}" "${{ inputs.client_payload }}" "${{ inputs.wait_interval }}"
      shell: bash
