name: Trigger Regression

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment to test (dev|perf|staging)"
        default: "perf"
        required: true
        type: string
      branch:
        description: "Git branch to use in the private repo"
        required: true
        type: string

jobs:
  run-regression:
    name: "Set up regression for ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Trigger Regression Workflow
        uses: ./.github/actions/workflow-trigger-and-wait
        with:
          owner: cris-oddball
          repo: hello-world
          github_token: ${{ secrets.DISPATCH_PAT }}
          workflow_file_name: run-tests.yml
          ref: ${{ inputs.branch }}
          client_payload: '{"environment": "${{ inputs.environment }}", "branch": "${{ github.ref }}" }'
          wait_interval: 10
          # may not include these
          #propagate_failure: true
          #trigger_workflow: true
          #wait_workflow: true

