name: Trigger Regression

on:
  workflow_call:
    inputs:
      environment:
        description: "Deployment environment to test (dev|perf|staging)"
        default: "perf"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment to test (dev|perf|staging)"
        default: "perf"
        required: true
        type: string

jobs:
  run-regression:
    name: "set up regression for ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Trigger and Wait for Workflow
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.DISPATCH_PAT }}
        script: |
          const path = '.github/scripts/trigger-regression.js';
          const triggerAndWait = require(path);
          triggerAndWait({github, context, core});

