name: Trigger Regression

on:
  workflow_call:
    inputs:
      environment:
        description: "Deployment environment to test (dev|perf|staging)"
        default: "perf"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment to test (dev|perf|staging)"
        default: "perf"
        required: true
        type: string

jobs:
  run-regression:
    name: "set up regression for ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.DISPATCH_PAT }}
        script: |
          const result = await github.rest.repos.createDispatchEvent({
            owner: 'cris-oddball',
            repo: 'hello-world',
            event_type: 'run_regression',
            client_payload: {"environment": "${{ inputs.environment }}"}
          })
          console.log(result);
